from enum import StrEnum


class CategoriaBemEstar(StrEnum):
    BEM_ESTAR_GERAL = "BEM_ESTAR_GERAL"
    POS_MASSAGEM = "POS_MASSAGEM"
    ERGONOMIA = "ERGONOMIA"
    HIDRATACAO = "HIDRATACAO"
    DESCANSO_RELAXAMENTO = "DESCANSO_RELAXAMENTO"
    FORA_DO_LIMITE_PROFISSIONAL = "FORA_DO_LIMITE_PROFISSIONAL"
    SINAL_DE_ALERTA = "SINAL_DE_ALERTA"
