from enum import StrEnum


class Intencao(StrEnum):
    AGENDAMENTO = "AGENDAMENTO"
    ORIENTACAO_BEM_ESTAR = "ORIENTACAO_BEM_ESTAR"
    SAUDE_SENSIVEL = "SAUDE_SENSIVEL"
    FORA_DE_ESCOPO = "FORA_DE_ESCOPO"
    NAO_ENTENDIDO = "NAO_ENTENDIDO"
